### PR TITLE
Fewer spaces

### LINKED ISSUE #75: Too many spaces
#67 broke `pPrintString "2020-08-22"`, along with other "broken" Show output from the `time` package.

Previous output:
```haskell
2020-08-22
```

Now:
```haskell
2020 - 08 - 22
```

The printer receives:
```haskell
[NumberLit "2020",Other "-",NumberLit "08",Other "-",NumberLit "22"] :: [Expr]
```

I'd say it actually does the right thing, since for most combinations of `Expr` we do want to insert spaces. So I'd class this as an error in the parser, which should instead just return [Other "2020-08-22"]. But this is perhaps a matter of opinion. We would lose syntax highlighting, which I'm fine with, since this isn't an actual numeric literal.

PS. I kept the example simple for the sake of discussion. To demonstrate that this really is an issue consider the readability of `2019 - 02 - 18 20 : 56 : 24.265489 UTC`.

### PR DESCRIPTION
**Pull request by georgefst**
Closes #75.

# to do
- [x] clean up
- [x] add regression tests with inputs from https://github.com/cdepillabout/pretty-simple/issues/75
- [x] for posterity, explain why this fixes everything

### CODE REVIEW

File: src/Text/Pretty/Simple.hs [hunk 1]
```diff
@@ -389,7 +389,7 @@ pHPrintStringNoColor = pHPrintStringOpt NoCheckColorTty defaultOutputOptionsNoCo
 -- | Like 'pShow', but without color.
 --
 -- >>> pShowNoColor [ Nothing, Just (1, "hello") ]
--- "[ Nothing\n, Just\n    ( 1\n    , \"hello\"\n    )\n]"
+-- "[ Nothing\n, Just \n    ( 1\n    , \"hello\"\n    )\n]"
```
Comment (georgefst) [inline src/Text/Pretty/Simple.hs:392]: Do we care about this? I personally don't. I think there are probably other cases where we have some trailing whitespace but our tests don't catch this when we use `pPrint` and similar rather than showing the string.

Comment (georgefst) [reply src/Text/Pretty/Simple.hs:392]: Ok, looking at the history, it seems this was explicitly implemented in https://github.com/cdepillabout/pretty-simple/pull/62. I'll fix it now.

File: src/Text/Pretty/Simple.hs [hunk 2]
```diff
@@ -688,6 +688,29 @@ layoutStringAnsi opts = fmap convertStyle . layoutString opts
...
+-- A @"type" 1
+--
+-- >>> pPrintString "2+2"
+-- 2+2
+--
+-- >>> pPrintString "1.0e-2"
+-- 1.0e-2
+--
+-- >>> pPrintString "0x1b"
+-- 0x1b
```
Comment (cdepillabout) [inline src/Text/Pretty/Simple.hs:712]: Thanks for the examples!

**Review by cdepillabout — APPROVED** [review]
Great, thanks for working on this!

This looks good to me.

You want to add a CHANGELOG and make a release?

**Comment by georgefst** [comment]
> You want to add a CHANGELOG and make a release?

I'm inclined to wait a few days, to see if anyone has any concerns (https://github.com/cdepillabout/pretty-simple/issues/75#issuecomment-1080999241). If there's no response, I'll release on the weekend.

**Comment by cdepillabout** [comment]
That sounds good to me!

**Comment by georgefst** [comment]
Actually, I'll do it now. I don't know if I'll have time on the weekend.
